### ISSUE TITLE
support ArrayIndexOutOfBoundsException in Super Dev Mode

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8257]
Originally reported on Google Code with ID 8268
```
Super Dev Mode compiles the entire GWT app to JavaScript, which means that we don't
check array access like in "classic" DevMode. We should probably generate JavaScript
runtime checks for this. This will slow down execution so maybe it needs to be an option.


```

Reported by `skybrian@google.com` on 2013-07-18 16:54:57

**Comment by dankurka** [comment]
I think this is solved by our InternalChecks

**Comment by gkdn** [comment]
We are still not checking Array indices in SDM but JRE also relies on them being not checked so this is unlikely to be addressed right now.
