### ISSUE TITLE
Compiler error 2.8: The method createFrom(T[], int) is undefined for the type Array

### ISSUE THREAD

**Issue by natros** [gwtproject/gwt#9173]
The last 2.8-snapshot won't compile guava-gwt-18.0
```
[INFO]    Tracing compile failure path for type 'com.google.common.collect.GwtPlatform'
[INFO]       [ERROR] Errors in 'jar:file:/Users/fsousa/.m2/ipb/com/google/guava/guava-gwt/18.0/guava-gwt-18.0.jar!/com/google/common/collect/super/com/google/common/collect/GwtPlatform.java'
[INFO]          [ERROR] Line 38: The method createFrom(T[], int) is undefined for the type Array
[INFO]    [ERROR] Aborting compile due to errors in some input files
```

Thank you.

**Comment by jnehlmeier** [comment]
This has already been fixed in Guava (they had used a private GWT API that has been removed). Either use Guava 19-SNAPSHOT or do not update to the latest GWT snapshot build until Guava 19 has been released.

**Comment by natros** [comment]
ok. it's seems to be woking with the last guava snapshot.

thank you

**Comment by csrinaldi** [comment]
I tried using "guava 19-rc1" but the error persists.
What repository must be included to use the snapshot?

**Comment by ekuefler** [comment]
rc1 doesn't have the fix in it. You have to download a snapshot release from https://oss.sonatype.org/content/repositories/snapshots/com/google/guava/guava/19.0-SNAPSHOT/

**Comment by jerith666** [comment]
The fix in Guava is https://github.com/google/guava/commit/9e56ef17c335319d21f1f2c454176c9d32687a59, FWIW.

**Comment by confile** [comment]
I use Guava 19 but the error is still present.

**Comment by jnehlmeier** [comment]
@confile the fix is not part of guava 19 release because Guava 19 wants to be compatible with older GWT releases. Use 20-SNAPSHOT instead.

**Comment by confile** [comment]
@jnehlmeier thanks 20.0-SNAPSHOT works fine.
