### ISSUE TITLE
JsInterop strange ReferenceError 

### ISSUE THREAD

**Issue by rhmoller** [gwtproject/gwt#9244]
I am experiencing strange ReferenceErrors with latest GWT snapshot: 

https://oss.sonatype.org/content/repositories/google-snapshots/com/google/gwt/gwt-user/2.8.0-SNAPSHOT/gwt-user-2.8.0-20151211.054617-115.jar

I was refactoring my code. And code that worked in the main entry point no longer works when moved into another class that is executed on a click event.

If I switch to the beta1 release then the ReferenceErrors go away - but then I don't have the varargs support.

I have not isolated the issue, but it can be seen in the menusystem branch on https://github.com/rhmoller/embrace

**Comment by rhmoller** [comment]
I have isolated the problem into a smaller project. 

Run it with  ./gradlew run
Then browse to http://localhost:8888/probe.interop.ProbeInterop/
Click the text

In the browser console you will see something like: ReferenceError: Y2_g$ is not defined

now change the class probe.interop.client.Main by enabling the works() method instead of the fails() method.

[probeinterop.zip](https://github.com/gwtproject/gwt/files/59837/probeinterop.zip)

**Comment by rhmoller** [comment]
By triaging the build logs I found that this has been broken since [0d84721](https://gwt.googlesource.com/gwt/+/0d84721e175734a9efc00e0ed6f1d01310a5ea2a)

**Comment by rhmoller** [comment]
Oh sorry. I think the error was partly on me.

After I fixed my generator so *callback* interfaces such as EventListener are marked with @JsFunction instead of @JsType it works fine with the latest 2.8.0-SNAPSHOT.

But it is suspicious that the first event listener works and the nested one fails, so there might still be an issue inside JsInterop.

**Comment by gkdn** [comment]
Is there a still a problem here in the snapshots? If there is, can you make sure you are using the new annotations and there are no warnings?

**Comment by rhmoller** [comment]
Yes, it still fails with the snapshots, but I think was using it wrong. 

I had EventListener defined as 

```java
@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public interface EventListener {
    void handleEvent(Event event);
}
```

But after changing it to  `@JsFunction` it works fine with the snapshot.

```java
@JsFunction
public interface EventListener {
    void handleEvent(Event event);
}
```

So what is left in this issue is my confusion about the way it fails when I erroneously mark the EventListener interface as a native type. I don't know whether you have any chance of catching such a mistake and make a warning for it.

Otherwise you may close this issue.

**Comment by gkdn** [comment]
Yeah, we can't do much on such mistakes.
