### ISSUE TITLE
Some libraries rely on identity of Object that makes GWT harder to integrate after 262fe4

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9405]
Some libraries (e.g. Polymer) uses type === Object or instanceof Object that makes GWT harder to integrate after https://gwt-review.googlesource.com/#/c/15520/

**Comment by jhorsley** [comment]
We've been impacted by this for the "instanceof Array" case. Are there plans to fix before 2.8 GA?

**Comment by gkdn** [comment]
We are working on it. What library is using "instanceof Array"?

**Comment by jhorsley** [comment]
Luckily for us it was an in-house JS library that was owned by a team who were willing to work with us on switching to Array.isArray(). I can see how it might be generally tricky for third-party js lib integration where it's not as easy to get the library changed though.

Glad to hear you guys are working on it already. Thanks!

**Comment by rluble** [comment]
Fixed by https://gwt-review.googlesource.com/#/c/16720/

**Comment by jhorsley** [comment]
I've pulled in the latest commit but the code that used to work with "instanceof Array" in beta2 still isn't working. FWIW the variable resolves that to true from inside the GWT code but when we call out into the JS lib (which is injected into TOP_WINDOW via ScriptInjector) "instanceof Array" resolves to false. The JsInterop method interface looks roughly like the following and then the JS lib has some code that gets called when that property changes that validates "foos" is an array using instanceof Array 

@JsOverlay 
public void setFoos( Foo[] foos ) {
 this.foos = foos;
}

I can try to come up with a minimal repro case but this is behaviour change between beta2 and rc2

**Comment by jhorsley** [comment]
Here's a repro case that throws an error from JS. Not sure if I'm doing something wrong?

window.FooTest = (function () {
    var FooTest = {};
    FooTest.setFoos = function (val) {
        if (!(val instanceof Array)) {
            throw new Error("val must be an array but was " + val + " (" + typeof (val) + ")");
        }
    };
    return FooTest;
}());

public class MyEntryPoint implements EntryPoint {

    @JsMethod(namespace = "FooTest")
    public static native void setFoos(MyEntryPoint.Foo[] foos);

    public interface FooResources extends ClientBundle {
        @Source( "foo.js" )
        TextResource fooScript();
    }

    @JsType
    public class Foo {
        public String bar;
    }

    @Override public void onModuleLoad() {
        ScriptInjector
                .fromString(((FooResources)GWT.create(FooResources.class)).fooScript().getText())
                .setWindow(ScriptInjector.TOP_WINDOW)
                .setRemoveTag(false)
                .inject();
        Foo foo1 = new Foo();
        foo1.bar = "one";
        Foo foo2 = new Foo();
        foo2.bar = "two";

        MyEntryPoint.setFoos( new Foo[] { foo1, foo2 } );        
    }
}

**Comment by jhorsley** [comment]
I also tried using

@JsType(isNative = true, namespace = JsPackage.GLOBAL )
public final class FooTest {
    public static native boolean setFoos(MyEntryPoint.Foo[] foos);
}

FooTest.setFoos( new Foo[] { foo1, foo2 } );

**Comment by rluble** [comment]
You should use Array.isArray instead of instanceof Array. Or use a native 
```java
JsType(isNative=true, name ="Array", namespace = JsPackage.GLOBAL) 
class NativeArray { ... }
```
and do a Java instanceof NativeArray.

**Comment by jhorsley** [comment]
The initial problem came from an existing JS library my team uses that used "instanceof Array". In this specific case it was an in-house JS library and the other team who owned it were great about switching to Array.isArray but, since it worked fine in beta2, I was concerned about breakages with third-party JS libs I won't be able to make changes to.

**Comment by jhorsley** [comment]
Thanks for the quick responses from both yourself and Goktug btw

**Comment by gkdn** [comment]
mew Foo[] written in java should have never returned true to "instanceof Array" written in main window. We don't think anything has changed wrt this behavior from 2.7.

**Comment by jhorsley** [comment]
@gkdn you're totally right. In trying out different code permutations I'd forgotten that we previously were using our own equivalent to Roberto's NativeArray before. I've verified that it behaves as expected with @rluble 's fix if I use our original NativeArray version.

Thanks again for your help.

**Comment by jhorsley** [comment]
Out of interest, is there an expectation/contract that calls like "void setFoo( Foo[] foos )" will always pass Array.isArray() going forward? This will likely impact how people construct their JsInterop API's

**Comment by gkdn** [comment]
For near term, all GWT arrays will pass Array.isArray test. I think this might only change if (ever) GWT adapts typed-arrays (not planned).
